name: 1-Checkout-Build-Artifact

# This workflow will checkout the code, build the WAR file, and create an artifact for use in following workflows.
on:
  # Enables manual runs
  workflow_dispatch:
  # Runs "Every at 5:04" (see https://crontab.guru)
  schedule:
  - cron: "4 5 * * *"

jobs:
  Checkout-Build-Artifact:
    runs-on: [ubuntu-latest]
    steps:
   
# Checkout code
      - uses: actions/checkout@v2
    
# Setup Java
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8       
      - name: Build with Maven
        working-directory: ./app/
        run: mvn clean install

      - name: Download Veracode Wrapper
        run: curl -O https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/22.5.10.0/vosp-api-wrappers-java-22.5.10.0.jar

# Use the UploadAndScan action to submit the artifact for scanning for Policy      
      - name: Submit Policy scan
        env: 
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
        run: >
         java -jar vosp-api-wrappers-java-22.5.10.0.jar 
         -vid $vid
         -vkey $vkey 
         -appname PetStoreAPI-Github
         -action UploadAndScan
         -createprofile true
         -criticality Medium
         -version ${{ github.run_id }}
         -teams ClintPollock-DemoApps2023 
         -filepath app/target/verademo.war
        continue-on-error: true


# Use the UploadAndScan action to submit the artifact for scanning for Sandbox     
      - name: Submit Sandbox scan
        env: 
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
        run: >
         java -jar vosp-api-wrappers-java-22.5.10.0.jar 
         -vid $vid
         -vkey $vkey 
         -appname PetStoreAPI-Github
         -action UploadAndScan
         -createprofile false
         -createsandbox true
         -sandboxname DailyBuild
         -criticality Medium
         -version ${{ github.run_id }}
         -teams ClintPollock-DemoApps2023 
         -filepath app/target/verademo.war
        continue-on-error: true

# Use SCA Agent to scan repo and container
  SCA-Agent-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

# Scan the repo with SCA Agent
      - name: SCA Agent Repo Scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan app

# Scan the container repo with SCA Agent                
      - name: SCA Agent Container Scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --image veracodedemolabs/verademo-java-github:latest --json=SCA-Container-Results-${{ github.run_id }}.json
 
# Workflow to run DAST Scan against QA server. 
  Submit-DAST-Scan:
    runs-on: ubuntu-latest
    steps:            
      - uses: actions/checkout@v2
      
# Update the DAST Scan Name to be uniuqe using SED command         
      - name: Update DAST config file with uniuqe scan name
        run: |
         NOW=$(date +"%m-%d-%Y-%T")
         sed -i 's/VeraDemo-Java-GitHub/VeraDemo-Java-GitHub-'${NOW}'/g' vc-dast-config.json
         sed -i 's/verademo-java-github.qa/servicenow-verademo-java-github.qa/g' vc-dast-config.json

# Visual confirmation of the scan submission details
      - name: Display DAST config file with uniuqe scan name
        run: |
          cat vc-dast-config.json
 
# DAST scan submission using the DAST API 
      - name: Submit Veracode DAST Scan
        run: |
         pip install veracode-api-signing
         export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
         export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
         http --verbose --auth-type=veracode_hmac POST "https://api.veracode.com/was/configservice/v1/analyses?job_options=run_verification=false" < vc-dast-config.json
