name: Veracode

on:
  # Enables manual runs
  workflow_dispatch:
  # Runs "Every at 5:04" (see https://crontab.guru)
  schedule:
  - cron: "4 5 * * *"

jobs:
  SAST_Scan:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.1.3

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         ./veracode package -s . -a

      - name: SAST Scan
        continue-on-error: true
        run: |
         ./veracode static scan /home/runner/work/verademo-java/verademo-java/verademo.war --summary-output sast-summary.txt
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
